package com.mengyu.drools.attribute

import com.mengyu.drools.util.OutputDisplay;
import com.mengyu.drools.pojo.example.Apple;
import com.mengyu.drools.pojo.example.Ticket;

global OutputDisplay display;

//rule "Set a global variable"
//    when
//        eval(true)
//    then
//        display.showText("Hello World!");
//end

//
//rule "Test Agenda Group1"
//    agenda-group "Apple group"
//
//    when
//        $apple : Apple()
//    then
//        display.showText("There's an apple!");
//end
//
//rule "Test Agenda Group2"
//    agenda-group "Apple group"
//
//    when
//        $apple : Apple()
//    then
//        display.showText("There's an other apple!");
//end
//
//rule "Test Salience 1"
//    salience 3
//
//    when
//        $apple : Apple()
//    then
//        display.showText("I am No.1");
//end
//
//rule "Test Salience 2"
//    salience 2
//
//    when
//        $apple : Apple()
//    then
//        display.showText("I am No.2");
//end



//rule "Test no-loop 1"
//    no-loop false
//    when
//        $ticket: Ticket(amount > 0)
//    then
//        $ticket.setAmount($ticket.getAmount() + 1);
//         display.showText("The amount of ticket is "+ $ticket.getAmount());
//        update($ticket);
//end


//rule "Test no-loop 2"
//    no-loop true
//    when
//        $ticket: Ticket(amount > 0)
//    then
//        $ticket.setAmount($ticket.getAmount() + 1);
//        display.showText("The amount of ticket is "+ $ticket.getAmount());
//        update($ticket);
//end


//rule "Test date effective and date expire1"
//    date-effective "04-Nov-2020 19:00:00" //dd-MMM-yyyy
//    date-expires "05-Nov-2020"
//    when
//        Apple()
//    then
//        display.showText("Time flies using default date format");
//end


rule "Test date effective and date expire2"
    date-effective "2020-11-04 13:30:00"
    date-expires "2020-11-04 16:32:00"
    when

    then
        display.showText("Time flies using customized date format");
end

