package com.ubr.drools.apple

import  com.ubr.drools.pojo.example.Apple;
import java.util.ArrayList

rule "Create an apple1"

    when

    then
        System.out.println("There's no apple!");
end


rule "Test define a class"

    when
        eval(true)
    then
        City city = new City();
        city.setName("Beijing");
        System.out.println(city.getName());
        printLine();

end

rule "Test define a class2"

    when
        eval(true)
    then
        City city = new City(1, "Beijing");
        System.out.println(city.getId() + " ," + city.getName());
        printLine();

end

rule "Test define a class3"

    when
        eval(true)
    then
        City city = new City(1);
        System.out.println(city.getId());
        printLine();

end

rule "Create an apple2"

    when
        Apple()
    then
        System.out.println("There's an apple!");
end


rule "Filter red apples"

    when
        $apple : Apple("red" == colour)
    then
        System.out.println("There's a red apple!");
        printLine();
end


rule "An apple which's greater than 50g"

    when

        $apple : Apple($weight: weight, $weight > 50)
    then
        System.out.printf("There's a %s apple, its weight is %s%n", $apple.getColour(), $weight);
         printLine();
end

//rule "greater than 50g"
//
//    when
//        $apple : Apple($weight: weight, $weight > 50)
//    then
//        System.out.println("There's a " + $apple.getColour() + " apple, its weight is " + $weight);
//        printLine();
//end


rule "Find an apple in the blanket"

    when
        $list: ArrayList(size > 0 )
            from collect(Apple(weight > 50))
    then
        for (Object ff : $list){
            Apple apple = (Apple)ff;
            System.out.println("I find a " + apple.getColour() + " apple, its weight is " + apple.getWeight());
        }
         printLine();
end
//
//
function void printLine(){
        System.out.println("====================================");
}


declare City
    id : Integer @key
    name : String
end



